$(document).ready(function(){
	/*$("#usersearchicon").click(function(){
			$(".mainhead").hide();
			$("#usersearchhead").show();
		});
	$(".content-main").click(function(){
			$("#usersearchhead").hide();
			$(".mainhead").show();
	});*/
	//$("#asquero-logo").css({"width":"asqlogowidth","height":"auto"});
	/*$("#hello_message").hover(function(){
		$("#profilepagelink").css("color","#922B21");
		$("#hello_message").css("background-color","white");
	},
	function(){
		$("#profilepagelink").css("color","white");
		$("#hello_message").css("background-color","#922B21");
	});*/

	/*$("#usersignout").hover(function(){
		$("#signoutlink").css("color","#922B21");
		$("#usersignout").css("background-color","white");
	},
	function(){
		$("#signoutlink").css("color","white");
		$("#usersignout").css("background-color","#922B21");
	});

	$("#userwrite").hover(function(){
		$("#writelink").css("color","#922B21");
		$("#userwrite").css("background-color","white");
	},
	function(){
		$("#writelink").css("color","white");
		$("#userwrite").css("background-color","#922B21");
	});

	$("#usersearchicon").hover(function(){
		$("#fa-searchicon").css("color","#922B21");
		$("#usersearchicon").css("background-color","white");
	},
	function(){
		$("#fa-searchicon").css("color","white");
		$("#usersearchicon").css("background-color","#922B21");
	});*/
});
